<section class="subhead">
	<div class="subhead-text">
		<h1>Découvrez l'intégralité des podcasts de RadioKawa</h1>
		<div class="subhead-button">
			<button class="subhead-play">
				<a rel="tab" href="/podcasts/radiokawa/">Découvrir</a> 
				<i class="fa fa-arrow-circle-right fa-3x"></i>
			</button>
		</div>	
	</div>
</section> 
<div class="clearfix"></div>
<div class="container">

	<section class="newPod pull-left">
		<div class="title-head">
			<div class="pull-left">
				<h2>Nouveaux podcasts</h2>
			</div>
			<div class="plus pull-right">
				<!-- <a href="">Plus de nouveautés</a><i class="fa fa-chevron-right"></i> -->
			</div>
		</div>
		<ul class="thumbnails">
			<?php foreach ($podcasts as $podcast): ?>			
			<li>
				<div class="posted"> 
					<h4><?php echo $podcast['category_name']; ?></h4>
				</div>	
				<div class="button-group">
					<a href="<?php echo $podcast['guid']; ?>" class="audioelement toplaylist" data-id="<?php echo $podcast['emm_id']; ?>">
						<button class="btn btn-add" title="Ajouter à la liste de lecture"> 
							<i class="fa fa-plus"></i>
						</button>
					</a>
				</div>
				<figure>
					<div class="buttonplay">
						<a href="<?php echo $podcast['guid']; ?>" class="audioelement toplay" data-id="<?php echo $podcast['emm_id']; ?>"></a>
					</div>
						<img src="<?php echo $podcast['image']; ?>" alt="<?php echo $podcast['podcast_title']; ?>" width="160" height="160" />
					<figcaption>
						<span class="titre"><a href="/podcasts/<?php echo $podcast['name']; ?>/<?php echo slugify(str_replace(' ', '', $podcast['podcast_title'])); ?>/" rel="tab"><?php echo $podcast['podcast_title']; ?></a></span>
						<span class="auteur"><a href="/podcasts/<?php echo $podcast['name']; ?>/" rel="tab"><?php echo $podcast['author']; ?></a></span>
					</figcaption>
				</figure>
			</li> 
		<?php endforeach ?>
		</ul>
	</section>	
	<section class="newEmission pull-left">
		<div class="title-head">
			<div class="pull-left">
				<h2>Dernières émissions</h2>
			</div>
			<div class="plus pull-right">
				<!-- <a href="">Plus d'émissions</a><i class="fa fa-chevron-right"></i> -->
			</div>
		</div>
			<ul class="thumbnails"> 
				<?php foreach ($emissions as $emission): ?>			
					<li>
						<div class="posted">
							<h4><?php echo $emission['category_name']; ?></h4>
						</div>	
						<figure>
							<a href="/podcasts/<?php echo $emission['name']; ?>/<?php echo slugify(str_replace(' ', '', $emission['podcast_title'])); ?>/" rel="tab">
								<img src="<?php echo $emission['image']; ?>" alt="<?php echo $emission['podcast_title'] ?>" width="160" height="160" />
							</a>
							<figcaption>
								<span class="titre"><a href="/podcasts/<?php echo $emission['name']; ?>/<?php echo slugify(str_replace(' ', '', $emission['podcast_title'])); ?>/" rel="tab"><?php echo $emission['podcast_title']; ?></a></span>
								<span class="auteur"><a href="/podcasts/<?php echo $emission['name']; ?>/" rel="tab"><?php echo $emission['author']; ?></a></span>
							</figcaption>
						</figure>
					</li>
				<?php endforeach ?>
			</ul>
	</section> 
</div>	
<div class="clearfix"></div>
<footer>
<!-- 	<ul>
		<li><a href="">Contact</a></li>
		<li><a href="">Mentions Légales</a></li>
	</ul> -->
</footer>
<div id="filter"></div> 

<!-- SCRIPTS -->
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<?php if(!isset($_GET['rel'])): ?>
	<script src="<?php echo $js_dir; ?>reload.js?<?php echo time(); ?>"></script>
<?php endif; ?>
<script src="<?php echo $js_dir; ?>search.js?<?php echo time(); ?>"></script>
<script src="<?php echo $js_dir; ?>layout.js?<?php echo time(); ?>"></script>
<script src="<?php echo $js_dir; ?>player/player.js?<?php echo time(); ?>"></script>
<script src="<?php echo $js_dir; ?>player/myplayer.js?<?php echo time(); ?>"></script>
<script src="<?php echo $js_dir; ?>connexionFB.js?<?php echo time(); ?>"></script>

</body>
</html>

