	<div id="content">
		<div class="img-container">
			<img src="<?php echo $img_dir; ?>radioKawa.png" width="100%" alt="RadioKawa" onmousedown="return false;" />
			<h1 class="img-title"></h1>
		</div>
		<div class="bottom-content">
			<section>
				<div class="title-head">
					<h2>Nouveaux podcasts</h2>
					<span><a href="#">Plus de nouveautés</a></span>
				</div>
				<ul class="thumbnails">
					<li>
						<figure>
							<div class="container_playButton">
								<div class="hole">
									<div class="playButton">
										<div class="triangle"><i class="fa fa-play fa-2x"></i></div>
										<div class="lighter_triangle"></div>
										<div class="darker_triangle"></div>
									</div>
								</div>
							</div>
							<a href="#"><img src="<?php echo $img_dir; ?>LesPlanetes.jpg" alt="Podcast1" width="150" height="150" /></a>
							<figcaption>
								<span class="auteur"><a href="#">RadioKawa</a></span>
								<span class="titre"><a href="#">Les Planètes</a></span>
							</figcaption>
						</figure>
					</li>
					<li>
						<figure>
							<div class="container_playButton">
								<div class="hole">
									<div class="playButton">
										<div class="triangle"><i class="fa fa-play fa-2x"></i></div>
										<div class="lighter_triangle"></div>
										<div class="darker_triangle"></div>
									</div>
								</div>
							</div>
							<a href="#"><img src="<?php echo $img_dir; ?>loljapon.jpg" alt="Podcast1" width="150" height="150" /></a>
							<figcaption>
								<span class="auteur"><a href="#">RadioKawa</a></span>
								<span class="titre"><a href="#">LolJapon</a></span>
							</figcaption>
						</figure>
					</li>
					<li>
						<figure>
							<div class="container_playButton">
								<div class="hole">
									<div class="playButton">
										<div class="triangle"><i class="fa fa-play fa-2x"></i></div>
										<div class="lighter_triangle"></div>
										<div class="darker_triangle"></div>
									</div>
								</div>
							</div>
							<a href="#"><img src="<?php echo $img_dir; ?>LesPlanetes.jpg" alt="Podcast1" width="150" height="150" /></a>
							<figcaption>
								<span class="auteur"><a href="#">RadioKawa</a></span>
								<span class="titre"><a href="#">Les Planètes</a></span>
							</figcaption>
						</figure>
					</li>
					<li>
						<figure>
							<div class="container_playButton">
								<div class="hole">
									<div class="playButton">
										<div class="triangle"><i class="fa fa-play fa-2x"></i></div>
										<div class="lighter_triangle"></div>
										<div class="darker_triangle"></div>
									</div>
								</div>
							</div>
							<a href="#"><img src="<?php echo $img_dir; ?>loljapon.jpg" alt="Podcast1" width="150" height="150" /></a>
							<figcaption>
								<span class="auteur"><a href="#">RadioKawa</a></span>
								<span class="titre"><a href="#">LolJapon</a></span>
							</figcaption>
						</figure>
					</li>
					<li>
						<figure>
							<div class="container_playButton">
								<div class="hole">
									<div class="playButton">
										<div class="triangle"><i class="fa fa-play fa-2x"></i></div>
										<div class="lighter_triangle"></div>
										<div class="darker_triangle"></div>
									</div>
								</div>
							</div>
							<a href="#"><img src="<?php echo $img_dir; ?>e-Dixit.jpg" alt="Podcast1" width="150" height="150" /></a>
							<figcaption>
								<span class="auteur"><a href="#">RadioKawa</a></span>
								<span class="titre"><a href="#">E-dixit</a></span>
							</figcaption>
						</figure>
					</li>
					<li>
						<figure>
							<a href="#"><img src="<?php echo $img_dir; ?>MorceauxChoisis.jpg" alt="Podcast1" width="150" height="150" /></a>
							<figcaption>
								<span class="auteur"><a href="#">RadioKawa</a></span>
								<span class="titre"><a href="#">Morceaux Choisis</a></span>
							</figcaption>
						</figure>
					</li>
					<li>
						<figure>
							<a href="#"><img src="<?php echo $img_dir; ?>GaleriaLudica.jpg" alt="Podcast1" width="150" height="150" /></a>
							<figcaption>
								<span class="auteur"><a href="#">RadioKawa</a></span>
								<span class="titre"><a href="#">Galeria Ludica</a></span>
							</figcaption>
						</figure>
					</li>
					<li>
						<figure>
							<a href="#"><img src="<?php echo $img_dir; ?>MorceauxChoisis.jpg" alt="Podcast1" width="150" height="150" /></a>
							<figcaption>
								<span class="auteur"><a href="#">RadioKawa</a></span>
								<span class="titre"><a href="#">Morceaux Choisis</a></span>
							</figcaption>
						</figure>
					</li>
					<li>
						<figure>
							<a href="#"><img src="<?php echo $img_dir; ?>GaleriaLudica.jpg" alt="Podcast1" width="150" height="150" /></a>
							<figcaption>
								<span class="auteur"><a href="#">RadioKawa</a></span>
								<span class="titre"><a href="#">Galeria Ludica</a></span>
							</figcaption>
						</figure>
					</li>
					<li>
						<figure>
							<a href="#"><img src="<?php echo $img_dir; ?>MorceauxChoisis.jpg" alt="Podcast1" width="150" height="150" /></a>
							<figcaption>
								<span class="auteur"><a href="#">RadioKawa</a></span>
								<span class="titre"><a href="#">Morceaux Choisis</a></span>
							</figcaption>
						</figure>
					</li>
					<li>
						<figure>
							<a href="#"><img src="<?php echo $img_dir; ?>GaleriaLudica.jpg" alt="Podcast1" width="150" height="150" /></a>
							<figcaption>
								<span class="auteur"><a href="#">RadioKawa</a></span>
								<span class="titre"><a href="#">Galeria Ludica</a></span>
							</figcaption>
						</figure>
					</li>
				</ul>	
				<div class="clearfix"></div>
				<div class="title-head">
					<h2>Derniers podcasts</h2>
				</div>
				<ul class="thumbnails">
					<li>
						<figure>
							<a href="#"><img src="<?php echo $img_dir; ?>PoR01/HotlineGianni.jpg" alt="Podcast1" width="150" height="150" /></a>
							<figcaption>
								<span class="auteur"><a href="#">Auteur du podcast</a></span>
								<span class="titre"><a href="#">Titre du podcast</a></span>
							</figcaption>
						</figure>
					</li>
					<li>
						<figure>
							<a href="#"><img src="<?php echo $img_dir; ?>PoR01/BoudoirGambetta.jpg" alt="Podcast1" width="150" height="150" /></a>
							<figcaption>
								<span class="auteur"><a href="#">Auteur du podcast</a></span>
								<span class="titre"><a href="#">Titre du podcast</a></span>
							</figcaption>
						</figure>
					</li>
					<li>	
						<figure>
							<a href="#"><img src="<?php echo $img_dir; ?>PoR01/EmissionsSpeciales.jpg" alt="Podcast1" width="150" height="150" /></a>
							<figcaption>
								<span class="auteur"><a href="#">Auteur du podcast</a></span>
								<span class="titre"><a href="#">Titre du podcast</a></span>
							</figcaption>
						</figure>
					</li>
					<li>
						<figure>
							<a href="#"><img src="<?php echo $img_dir; ?>PoR01/InferieurATrois.jpg" alt="Podcast1" width="150" height="150" /></a>
							<figcaption>
								<span class="auteur"><a href="#">Auteur du podcast</a></span>
								<span class="titre"><a href="#">Titre du podcast</a></span>
							</figcaption>
						</figure>
					</li>
					<li>
						<figure>
							<a href="#"><img src="<?php echo $img_dir; ?>PoR01/PasseleStick.jpg" alt="Podcast1" width="150" height="150" /></a>
							<figcaption>
								<span class="auteur"><a href="#">Auteur du podcast></a></span>
								<span class="titre"><a href="#">Titre du podcast</a></span>
							</figcaption>
						</figure>
					</li>
				</ul>
				<div class="clearfix"></div>
			</section>
			<section class="social">
				<div>
					<h3 class="sidebar-header">
						<i class="fa fa-group fa-2x"></i>
						<span>Activité de mes amis</span>
					</h3>
					<div class="suggestionAmi">
						<ul class="list">
							<li>
								<div>
									<div>
										<img src="<?php echo 	$img_dir; ?>ami1.jpg" 	width="80" height="80">
									</div>
									<div class="titreAmi">
										<h3>James Plain</h3>
									</div>
									<div class="stats">
										<span>3000 abonnés</span>
										<button><i class=" fa fa-plus"></i>Suivre</button>
									</div>
								</div>
							</li>
						</ul>
					</div>
				</div>
			</section>
		</div>

