<div id="content">
		
		<div class="bottom-content">
			<ul class="thumbnails">
				<li>
					<a href="">
						<figure>
							<img src="<?php echo $img_dir; ?>LesPlanetes.jpg" alt="Podcast1" width="150" height="150">
							<figcaption>
								<span class="auteur"><a href="">Auteur du podcast</a></span>
								<span class="titre"><a href="">Titre du podcast</a></span>
							</figcaption>
						</figure>
					</a>
				</li>
				<li>
					<a href="">
						<figure>
							<img src="<?php echo $img_dir; ?>loljapon.jpg" alt="Podcast1" width="150" height="150">
							<figcaption>
								<span class="auteur"><a href="">Auteur du podcast</a></span>
								<span class="titre"><a href="">Titre du podcast</a></span>
							</figcaption>
						</figure>
					</a>
				</li>
				<li>
					<a href="">
						<figure>
							<img src="<?php echo $img_dir; ?>e-Dixit.jpg" alt="Podcast1" width="150" height="150">
							<figcaption>
								<span class="auteur"><a href="">Auteur du podcast</a></span>
								<span class="titre"><a href="">Titre du podcast</a></span>
							</figcaption>
						</figure>
					</a>
				</li>
				<li>
					<a href="">
						<figure>
							<img src="<?php echo $img_dir; ?>MorceauxChoisis.jpg" alt="Podcast1" width="150" height="150">
							<figcaption>
								<span class="auteur"><a href="">Auteur du podcast</a></span>
								<span class="titre"><a href="">Titre du podcast</a></span>
							</figcaption>
						</figure>
					</a>
				</li>
				<li>
					<a href="">
						<figure>
							<img src="<?php echo $img_dir; ?>GaleriaLudica.jpg" alt="Podcast1" width="150" height="150">
							<figcaption>
								<span class="auteur"><a href="">Auteur du podcast></a></span>
								<span class="titre"><a href="">Titre du podcast</a></span>
							</figcaption>
						</figure>
					</a>
				</li>
				<li>
					<a href="">
						<figure>
							<img src="<?php echo $img_dir; ?>PoR01/HotlineGianni.jpg" alt="Podcast1" width="150" height="150">
							<figcaption>
								<span class="auteur"><a href="">Auteur du podcast</a></span>
								<span class="titre"><a href="">Titre du podcast</a></span>
							</figcaption>
						</figure>
					</a>
				</li>
				<li>
					<a href="">
						<figure>
							<img src="<?php echo $img_dir; ?>PoR01/BoudoirGambetta.jpg" alt="Podcast1" width="150" height="150">
							<figcaption>
								<span class="auteur"><a href="">Auteur du podcast</a></span>
								<span class="titre"><a href="">Titre du podcast</a></span>
							</figcaption>
						</figure>
					</a>
				</li>
				<li>
					<a href="">
						<figure>
							<img src="<?php echo $img_dir; ?>PoR01/EmissionsSpeciales.jpg" alt="Podcast1" width="150" height="150">
							<figcaption>
								<span class="auteur"><a href="">Auteur du podcast</a></span>
								<span class="titre"><a href="">Titre du podcast</a></span>
							</figcaption>
						</figure>
					</a>
				</li>
				<li>
					<a href="">
						<figure>
							<img src="<?php echo $img_dir; ?>PoR01/InferieurATrois.jpg" alt="Podcast1" width="150" height="150">
							<figcaption>
								<span class="auteur"><a href="">Auteur du podcast</a></span>
								<span class="titre"><a href="">Titre du podcast</a></span>
							</figcaption>
						</figure>
					</a>
				</li>
				<li>
					<a href="">
						<figure>
							<img src="<?php echo $img_dir; ?>PoR01/PasseLeStick.jpg" alt="Podcast1" width="150" height="150">
							<figcaption>
								<span class="auteur"><a href="">Auteur du podcast></a></span>
								<span class="titre"><a href="">Titre du podcast</a></span>
							</figcaption>
						</figure>
					</a>
				</li>
			</ul>
		</div>