<?php

// HTML initialization
if(!isset($_GET['rel'])){
	include 'templates/blocks/header.phtml';
}

// Include « navigation »
if(!isset($_GET['rel'])){
	include 'templates/blocks/left-sidebar.phtml';
}

?>

<?php

// Right column (or main content)
// Content depending on $_GET['page']
echo "<div id='content'>";
include 'templates/pages/'.$_GET['page'].'.phtml';
echo "</div>";

include 'templates/blocks/footer.phtml';