 <!doctype html>
<html lang="fr">
<head>
	<meta charset="UTF-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<title>PodZone » Your podcast Zone</title>
	<link rel="stylesheet" href="<?php echo $css_dir; ?>main.css"/>
	<link rel="stylesheet" href="<?php echo $css_dir; ?>player.css"/>
	<link rel="stylesheet" href="<?php echo $css_dir; ?>studio.css"/>
	<link rel="stylesheet" href="<?php echo $css_dir; ?>podcast.css"/>
	<link rel="stylesheet" href="<?php echo $css_dir; ?>search.css"/>
	<link rel="stylesheet" href="<?php echo $css_dir; ?>font-awesome.css"/>
	<link href='http://fonts.googleapis.com/css?family=Raleway+Dots|Raleway:400,300,700,600' rel='stylesheet' type='text/css'/>
</head>
<body>
	<header class="fixed-top"> 
		<div class="menu-button" onmousedown="return false;">
			<i class="fa fa-reorder"></i>
		</div>
		<div class="logo">
			<a href="/accueil/" rel="tab">Podzone</a>
		</div>
		<form class="navbar-search" role="search">
			<input class="search"type="text" placeholder="Rechercher un podcast, une émission, un épisode...">
			<button type="submit" class="button-search">
				<i class="fa fa-search fa-2x"></i>
			</button>	
		</form>
			<button class="btn-fb-connect" onclick="login()">
				<i class="fa fa-facebook-square fa-2x"></i>
					<span>Connexion avec Facebook</span>
			</button>
			<button class="btn-fb-connect-res">
				<i class="fa fa-facebook-square fa-2x"></i>
			</button>
	</header>

	<div id="search-results">
		<i class="fa fa-close"></i>
		<h3></h3>
		<div id="results"></div>
	</div>
		
	