<!doctype html>
<html lang="fr">
<head>
	<meta charset="UTF-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<title>PodZone » Your podcast Zone</title>

	<link rel="stylesheet" href="<?php echo $css_dir; ?>main.css" />
	<link rel="stylesheet" href="<?php echo $css_dir; ?>font-awesome.css" />
	<link href='http://fonts.googleapis.com/css?family=Raleway+Dots|Raleway:400,300,700,600' rel='stylesheet' type='text/css'>
</head>
<body>
	<header class="fixed-top">
		<div class="menu-button"><i class="fa fa-reorder fa-2x"></i></div>
		<div class="logo"><a href="">Podzone</a></div>
		<form class="navbar-search" role="search">
			<div class="form-group">
				<input type="text">
			</div>
			<button type="submit" class="button-search">
				<i class="fa fa-search fa-2x"></i>
			</button>	
		</form>
			<ul class="sign pull-right">
				<li><a href="">S'inscrire</a></li>
				<li><a href="">Connexion</a></li>
			</ul>
	</header>
		
	