		<section id="left-sidebar">

			

			<!--

			<nav>
				<ul>
					<li><a href="#">Accueil</a></li>
					<li><a href="#">Tous les podcasts</a></li>
					<li><a href="#">Explorer</a></li>
					<li><a href="#">Soumettre un podcast</a></li>
					<li><a href="#">Contact</a></li>
				</ul>
			</nav>

			<section id="audio-player">
				<img src="<?php echo $img_dir; ?>/podcasts/pochette_retrosphere.png" alt="Rétrosphère" />
				<audio preload="metadata">
					<source src="retrosphere_31.mp3" type="audio/mpeg"></source>
					Votre navigateur ne gère pas la lecture de fichier .mp3
				</audio>
				<div id="controls">
					<img src="<?php echo $img_dir; ?>/player/prev.png" class="prev" alt="Précédent" />
					<img src="<?php echo $img_dir; ?>/player/play.png" id="playpause" class="play" alt="Lecture" />
					<img src="<?php echo $img_dir; ?>/player/next.png" class="next" alt="Suivant" /> 
				</div>
			</section>
-->
		</section>
	