		<section id="left-sidebar">


			<nav class="sidebar-nav">
				<ul>
					<li>
						<div>
							<i class="fa fa-home"></i>
							<a href="#">Accueil</a>
						</div>	
					</li>
					<li>
						<div>
							<i class="fa fa-microphone"></i>
							<a href="#">Podcasts</a>
						</div>	
					</li>
					<li>
						<div>
							<i class="fa fa-music"></i>
							<a href="#">Playlist</a>
						</div>
					</li>
					<li>
						<div>
							<i class="fa fa-upload"></i>
							<a href="#">Upload</a>
						</div>							
					</li>
					<li>
						<div>
							<i class="fa fa-group"></i>
							<a href="#">Amis</a>
						</div>
					</li>
				</ul>
			</nav>


		</section>
	